config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'quotes#index'
  resources :quotes
  get 'about', to: 'quotes#about'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/quote.rb
class Quote < ApplicationRecord
  validates :saying, presence: true, length: { maximum: 140, minimum: 3 }
  validates :author, presence: true, length: { maximum: 50, minimum: 3 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
  def index
    @quote = Quote.order("RANDOM()").first
  end

  def create #<-action
    @quote = Quote.create(quote_params)
    if @quote.invalid?
      flash[:error] = '<strong>Could not save</strong> the data you entered is invalid'
    end
    redirect_to root_path
  end

  def about

  end
  

  private

  def quote_params
    params.require(:quote).permit(:saying, :author)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Splurty</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
<!--NavBar Begin -->
    <header class="row">
      <div class="col-md-2 col-xs-12 offset-xs-5">
        <%= link_to root_path, class: 'logo' do %>
        <div class="circle">
          <br />
          We live
          <br />
          We do
          <br />
          We act
        </div>
        <% end %>
      </div>
      <div class="col-md-6 offset-1 col-sm-4 hidden-xs-down slogan">
      Splurting out actory stuff for actors who like to act.
      </div>
      <div class="col-md-3 offset-1 offset-sm-0 col-sm-5 links">
              <!-- Button trigger modal -->
        <%= link_to 'Contribute', new_quote_path, data: {toggle: 'modal', target: '#myModal'} %>
        &nbsp;
        &nbsp;
        <%= link_to 'About', about_path %>
      </div>

    </header>


    <!-- Modal -->
    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">×</span>
            </button>
            <h4 class="modal-title" id="myModalLabel">Contribute Your Quote</h4>
          </div>
          <%= simple_form_for Quote.new do |f| %>
            <div class="modal-body">
              <div class="form-group text-center mt-4 mr-2">
                <%= f.input :saying, label: "Quote", placeholder: " 140 Character Limit" %>
              </div>
              <div class="form-group text-center mr-2">
                <%= f.input :author, placeholder: " 40 Character Limit" %>
              </div> 
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
              <%= f.submit 'Create', class: 'btn btn-danger' %>
            </div>
          <% end %>
        </div>
      </div>
    </div>

    <hr />
<!--NavBar End -->

    <br class="clear" />
    <div class="container">
        <% if flash[:error].present? %>
          <div class="col-10 offset-1 alert alert-danger">
            <%= flash[:error].html_safe %>
          </div>
        <% end %>
    
      <%= yield %>
    
      
    </div>

<!-- ########  Footer begin ######## -->
    <div class="footer">
      <div class="container">
        <div class="row">
          <div class="col-12 col-sm-6">
            <%= link_to "This isn't enough, I need more cheesy goodness", root_path, class: 'next-quote' %>
          </div>
          <div class="col-12 col-sm-6 footer-blurb">
            Proudly hacked by <a href="#">Joshua Bangle</a><br />
            Want to build your own Splurty web app? - <a href="https://online.bootcampspot.com">Learn how to code here!</a>
          </div>
        </div>
      </div>
    </div>
<!-- ########   Footer end ####### -->

  </body>
 
</html>

app/views/quotes/about.html.erb
<div class="col-10 offset-1 about">
  <h1 class="about-title">About Splurty</h1>
  <div class="row">
    <div class="col-12 col-sm-4 about-image">
      <%= image_tag 'josh.jpg', class: 'rounded img-fluid' %>
    </div>
  </div>
  <br />
  <p>Splurty was built by Josh Bangle, a web developer from Dallas, TX. It's his very first web app, and that's probably pretty obvious.</p>
  
  <br />
  <p>Josh was able to make this app while learning to code at Boot Camp Spot. If you want to learn to code too, <a target="_blank" href="https://online.bootcampspot.com">start here</a>.</p>
</div>

app/views/quotes/index.html.erb
<div class="test-margin">
<h2 class="text-muted">Cheesy actor quote #<%= @quote.id %></h2>
<h1><%= @quote.saying %></h1>
<h2 class="text-right"><strong>-<%= @quote.author %></strong></h2>
</div>